services:
  ac-worldserver:
    environment:
      AC_AI_PLAYERBOT_RANDOM_BOT_AUTOLOGIN: "0"
      AC_AI_PLAYERBOT_MIN_RANDOM_BOTS: "0"
      AC_AI_PLAYERBOT_MAX_RANDOM_BOTS: "0"
      AC_AI_PLAYERBOT_DISABLED_WITHOUT_REAL_PLAYER: "1"
      AC_AI_PLAYERBOT_ADD_CLASS_ACCOUNT_POOL_SIZE: "6"
      AC_AI_PLAYERBOT_MAX_ADDED_BOTS: "5"
      AC_AI_PLAYERBOT_AUTO_GEAR_BIS_COMMAND: "1"
      AC_AI_PLAYERBOT_AUTO_GEAR_QUALITIY_LIMIT: "4"
      AC_AI_PLAYERBOT_MAX_PRIMARY_TRADE_SKILL: "11"
      AC_PLAYERBOTS_UPDATES_ENABLE_DATABASES: "1"
      AC_PLAYERBOTS_DATABASE_WORKER_THREADS: "1"
      AC_PLAYERBOTS_DATABASE_SYNCH_THREADS: "1"
    volumes:
      - ./modules:/azerothcore/modules:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
  ac-database:
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
  ac-authserver:
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
